name: Exponential Tree Branch
on:
  workflow_dispatch:
    inputs:
      level:
        description: 'Tree level (1, 2, 3, etc.)'
        required: true
        default: '1'
      parent:
        description: 'Parent repository'
        required: true
        default: '0x01'

jobs:
  branch-execution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        continue-on-error: true

      - name: Level ${{ github.event.inputs.level }} - Branch Analysis
        continue-on-error: true
        run: |
          nix-shell -p curl coreutils --run '
            echo "🌿 Level ${{ github.event.inputs.level }}: Branch from ${{ github.event.inputs.parent }}" > tree-level-${{ github.event.inputs.level }}.txt
            echo "Repository: $(echo ${{ github.repository }} | cut -d/ -f2)" >> tree-level-${{ github.event.inputs.level }}.txt
            echo "Timestamp: $(date)" >> tree-level-${{ github.event.inputs.level }}.txt
            curl -s ifconfig.me >> tree-level-${{ github.event.inputs.level }}.txt
          '

      - name: Spawn Next Level (if level < 3)
        if: ${{ github.event.inputs.level < '3' }}
        continue-on-error: true
        run: |
          CURRENT_LEVEL=${{ github.event.inputs.level }}
          NEXT_LEVEL=$((CURRENT_LEVEL + 1))
          REPO_NUM=$(echo ${{ github.repository }} | cut -d/ -f2 | sed 's/0x//')

          nix-shell -p github-cli coreutils --run '
            echo "🌳 Spawning Level '$NEXT_LEVEL' from Level '$CURRENT_LEVEL'"

            # Calculate next repository numbers (exponential: each spawns 3)
            BASE_NUM=$((($REPO_NUM - 1) * 3 + 5))
            REPO1=$(printf "0x%02x" $BASE_NUM)
            REPO2=$(printf "0x%02x" $((BASE_NUM + 1)))
            REPO3=$(printf "0x%02x" $((BASE_NUM + 2)))

            echo "Spawning to: $REPO1, $REPO2, $REPO3"

            gh workflow run exponential-tree-branch.yml --repo garmir/$REPO1 --field level='$NEXT_LEVEL' --field parent='${{ github.repository }}' 2>/dev/null || echo "$REPO1 queued" &
            gh workflow run exponential-tree-branch.yml --repo garmir/$REPO2 --field level='$NEXT_LEVEL' --field parent='${{ github.repository }}' 2>/dev/null || echo "$REPO2 queued" &
            gh workflow run exponential-tree-branch.yml --repo garmir/$REPO3 --field level='$NEXT_LEVEL' --field parent='${{ github.repository }}' 2>/dev/null || echo "$REPO3 queued" &

            echo "✅ Level '$NEXT_LEVEL' spawning complete"
          '

      - name: Ubuntu Fallback
        if: failure()
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y curl
          echo "✅ Ubuntu fallback - Level ${{ github.event.inputs.level }}" > fallback-branch.txt
          curl -s ifconfig.me >> fallback-branch.txt

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: exponential-tree-level-${{ github.event.inputs.level }}
          path: "tree-level-*.txt"
          retention-days: 1