name: Fixed Cascade Trigger
on: [workflow_dispatch, push]

jobs:
  cascade-trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        continue-on-error: true

      - name: Simple Cascade Execution
        continue-on-error: true
        run: |
          nix-shell -p curl coreutils --run '
            echo "Fixed cascade from $(echo ${{ github.repository }} | cut -d/ -f2)" > cascade-result.txt
            echo "Timestamp: $(date)" >> cascade-result.txt
            curl -s ifconfig.me >> cascade-result.txt
          '

      - name: Trigger Level 1 Using GitHub CLI
        continue-on-error: true
        run: |
          nix-shell -p github-cli --run '
            echo "🌳 Triggering Level 1 repositories using GitHub CLI"

            gh workflow run simple-working-cascade.yml --repo garmir/0x02 || echo "0x02 trigger attempted"
            gh workflow run simple-working-cascade.yml --repo garmir/0x03 || echo "0x03 trigger attempted"
            gh workflow run simple-working-cascade.yml --repo garmir/0x04 || echo "0x04 trigger attempted"

            echo "✅ Level 1 triggering complete via GitHub CLI"
          '

      - name: Ubuntu Fallback Trigger
        if: failure()
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y curl
          echo "Ubuntu fallback triggering Level 1" > fallback-trigger.txt

          # Simple HTTP trigger attempts
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/garmir/0x02/dispatches \
            -d '{"event_type":"cascade"}' || echo "0x02 fallback attempted"

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: fixed-cascade-results
          path: "*.txt"
          retention-days: 1