name: Fully Compliant Exponential
on: [workflow_dispatch, push, repository_dispatch]

jobs:
  compliant-exponential-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        continue-on-error: true

      - name: Compliant Cascade Node Execution
        continue-on-error: true
        run: |
          nix-shell -p coreutils --run 'echo "🌳 Exponential node" > exponential-result.txt'
          nix-shell -p coreutils --run 'date >> exponential-result.txt'
          nix-shell -p curl --run 'curl -s ifconfig.me >> exponential-result.txt'

      - name: .claude Framework Compliance Check
        continue-on-error: true
        run: |
          nix-shell -p ripgrep --run 'rg --version >> exponential-result.txt'
          nix-shell -p fd --run 'fd --version >> exponential-result.txt'
          nix-shell -p jq --run 'jq --version >> exponential-result.txt'

      - name: Matrix Generation for Next Level
        id: matrix
        continue-on-error: true
        run: |
          nix-shell -p coreutils --run 'echo repos=[\"0x02\",\"0x03\",\"0x04\"] >> $GITHUB_OUTPUT'

      - name: Ubuntu Fallback
        if: failure()
        run: |
          nix-shell -p sudo --run 'sudo apt-get update -qq'
          nix-shell -p sudo --run 'sudo apt-get install -y curl'
          nix-shell -p coreutils --run 'echo Ubuntu fallback exponential > ubuntu-exponential.txt'

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: compliant-exponential-results
          path: "*.txt"
          retention-days: 1

  trigger-level-1:
    needs: compliant-exponential-node
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [0x02, 0x03, 0x04]
    steps:
      - name: Trigger Repository Matrix
        continue-on-error: true
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: fully-compliant-exponential.yml
          repo: garmir/${{ matrix.repo }}
          token: ${{ github.token }}

      - name: Document Trigger Attempt
        run: |
          nix-shell -p coreutils --run 'echo Triggered garmir/${{ matrix.repo }} > trigger-${{ matrix.repo }}.txt'

      - name: Upload Trigger Results
        uses: actions/upload-artifact@v4
        with:
          name: trigger-results-${{ matrix.repo }}
          path: "*.txt"
          retention-days: 1