name: PAT Cascade Test
on: [workflow_dispatch, push, repository_dispatch]

jobs:
  pat-cascade-research:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        continue-on-error: true

      - name: Research PAT Cross-Repo Triggering
        continue-on-error: true
        run: |
          nix-shell -p curl coreutils --run '
            echo "🔬 PAT Cross-Repo Research Test" > pat-research.txt
            echo "Repository: $(echo ${{ github.repository }} | cut -d/ -f2)" >> pat-research.txt
            echo "Timestamp: $(date)" >> pat-research.txt
            echo "Event Type: ${{ github.event_name }}" >> pat-research.txt
          '
          nix-shell -p curl --run 'curl -s ifconfig.me >> pat-research.txt'

      - name: Test Repository Dispatch Method
        continue-on-error: true
        run: |
          nix-shell -p curl coreutils --run '
            echo "🧪 Testing Repository Dispatch API" >> pat-research.txt
            echo "Target: Next hex repository" >> pat-research.txt

            REPO_NUM=$(echo ${{ github.repository }} | cut -d/ -f2 | sed "s/0x//")
            REPO_NUM_DEC=$(echo "ibase=16; $REPO_NUM" | bc 2>/dev/null || echo "1")
            NEXT_REPO_NUM=$((REPO_NUM_DEC + 1))
            NEXT_REPO=$(printf "0x%02x" $NEXT_REPO_NUM)

            echo "Current: $(echo ${{ github.repository }} | cut -d/ -f2), Next: $NEXT_REPO" >> pat-research.txt
            echo "API Endpoint: repos/garmir/$NEXT_REPO/dispatches" >> pat-research.txt
          '

      - name: Document Cross-Repo Research
        continue-on-error: true
        run: |
          nix-shell -p ripgrep fd jq --run '
            echo "📊 .claude Methodology Research Results" >> pat-research.txt
            echo "Universal nix-shell: ✅ $(rg --version | head -1)" >> pat-research.txt
            echo "GitHub CLI capability: $(command -v gh >/dev/null && echo "Available" || echo "Not available")" >> pat-research.txt
            echo "Tool arsenal validated: fd $(fd --version), jq $(jq --version)" >> pat-research.txt
            echo "Research methodology: Following RECURSIVE_SUCCESS_METHODOLOGY.md" >> pat-research.txt
          '

      - name: Ubuntu Fallback Research
        if: failure()
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y curl bc
          echo "Ubuntu fallback: PAT research" > ubuntu-pat-research.txt
          echo "Cross-repo triggering requires PAT with repo scope" >> ubuntu-pat-research.txt

      - name: Upload Research Results
        uses: actions/upload-artifact@v4
        with:
          name: pat-cascade-research-results
          path: "*research.txt"
          retention-days: 7