name: Workflow Deployment Cascade
on: [workflow_dispatch, push]

jobs:
  level-0-deployer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        continue-on-error: true

      - name: Level 0 - Deploy Workflows to Level 1 Repos
        continue-on-error: true
        run: |
          # Create the branch workflow content
          cat > branch-workflow.yml << 'EOF'
          name: Exponential Branch
          on: [workflow_dispatch, push]
          jobs:
            branch-node:
              runs-on: ubuntu-latest
              steps:
                - uses: actions/checkout@v4
                - uses: DeterminateSystems/nix-installer-action@main
                  continue-on-error: true
                - name: Branch Analysis
                  run: |
                    nix-shell -p curl coreutils --run '
                      echo "🌿 Branch executing from $(echo ${{ github.repository }} | cut -d/ -f2)"
                      curl -s ifconfig.me > branch-ip.txt
                      echo "Timestamp: $(date)" >> branch-ip.txt
                    '
                - name: Deploy to Next Level
                  run: |
                    REPO_NUM=$(echo ${{ github.repository }} | cut -d/ -f2 | sed 's/0x//' | awk '{print strtonum("0x" $0)}')
                    NEXT_REPOS=("0x$(printf '%02x' $((REPO_NUM + 3)))" "0x$(printf '%02x' $((REPO_NUM + 6)))" "0x$(printf '%02x' $((REPO_NUM + 9)))")

                    for next_repo in "${NEXT_REPOS[@]}"; do
                      if [ "$next_repo" != "0x0f" ] && [ "$next_repo" != "0x12" ] && [ "$next_repo" != "0x15" ]; then
                        echo "Pushing workflow to $next_repo"
                        nix-shell -p github-cli coreutils --run "
                          echo 'Deploying to $next_repo from $(echo ${{ github.repository }} | cut -d/ -f2)'
                          gh api repos/garmir/\$next_repo/contents/.github/workflows/exponential-branch.yml --method PUT --field message='Exponential tree deployment' --field content='\$(base64 -w 0 branch-workflow.yml)' 2>/dev/null || echo '\$next_repo deployment queued'
                          gh workflow run exponential-branch.yml --repo garmir/\$next_repo 2>/dev/null || echo '\$next_repo triggered'
                        " &
                      fi
                    done
                    wait
                - name: Upload Results
                  uses: actions/upload-artifact@v4
                  with:
                    name: branch-results
                    path: "*.txt"
          EOF

          nix-shell -p github-cli coreutils --run '
            echo "🌳 Level 0: Deploying workflows to Level 1 branches"

            # Deploy branch workflow to 0x02, 0x03, 0x04
            for repo in 0x02 0x03 0x04; do
              echo "Deploying exponential branch workflow to $repo"
              gh api repos/garmir/$repo/contents/.github/workflows/exponential-branch.yml --method PUT \
                --field message="Exponential tree branch deployment from 0x01" \
                --field content="$(base64 -w 0 branch-workflow.yml)" 2>/dev/null || echo "$repo workflow exists"

              echo "Triggering workflow in $repo"
              gh workflow run exponential-branch.yml --repo garmir/$repo 2>/dev/null || echo "$repo triggered" &
            done

            wait
            echo "✅ Level 1 deployment and triggering complete"
          '

      - name: Ubuntu Fallback
        if: failure()
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y curl
          echo "✅ Ubuntu fallback - Level 0 deployment" > fallback-deploy.txt

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: exponential-tree-deployment
          path: "*.txt"
          retention-days: 1