name: Claude MD Analysis
on: [workflow_dispatch]
  
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        continue-on-error: true
      - name: Claude MD Analysis
        run: |
          nix-shell -p github-cli coreutils --run "echo Analysis complete"
