name: Globe Functionality Test
on: workflow_dispatch

jobs:
  test-globe-functionality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        continue-on-error: true

      - name: Test Globe Implementation (Claude Compliant)
        continue-on-error: true
        run: |
          nix-shell -p curl jq --run '
            echo "=== GLOBE FUNCTIONALITY TESTING ==="

            # Test if terminal globe script loads
            GLOBE_SCRIPT=$(curl -s https://garmir.github.io/garmir.io_assets/terminal-globe.js | wc -c)
            echo "Terminal globe script size: $GLOBE_SCRIPT bytes"

            # Test if main page references the script correctly
            SCRIPT_REF=$(curl -s https://garmir.github.io/ | grep -c "terminal-globe.js")
            echo "Script references found: $SCRIPT_REF"

            # Test interactive globe container
            GLOBE_CONTAINER=$(curl -s https://garmir.github.io/ | grep -c "interactive-globe")
            echo "Globe container found: $GLOBE_CONTAINER"

            # Test if GIF is removed
            GIF_REFS=$(curl -s https://garmir.github.io/ | grep -c "globe.gif")
            echo "GIF references remaining: $GIF_REFS"

            # Test geolocation API availability
            echo "Testing IP geolocation API..."
            IP_API_TEST=$(curl -s https://ipapi.co/json/ | jq -r .ip 2>/dev/null || echo "API_ERROR")
            echo "IP API response: $IP_API_TEST"

            echo "✅ Globe functionality test complete"
          '

      - name: Test Navigation Fixes (Claude Compliant)
        continue-on-error: true
        run: |
          nix-shell -p curl ripgrep --run '
            echo "=== NAVIGATION FUNCTIONALITY TESTING ==="

            # Test for remaining broken links
            BROKEN_LINKS=$(curl -s https://garmir.github.io/ | rg "href=\"#\"" -c)
            echo "Broken navigation links remaining: $BROKEN_LINKS"

            # Test functional navigation
            FUNCTIONAL_LINKS=$(curl -s https://garmir.github.io/ | rg "href=\"[^#]" -c)
            echo "Functional navigation links: $FUNCTIONAL_LINKS"

            # Test posts page navigation
            POSTS_NAV=$(curl -s https://garmir.github.io/posts.html | rg "drawer-link" -c)
            echo "Posts page navigation links: $POSTS_NAV"

            # Test projects page navigation
            PROJECTS_NAV=$(curl -s https://garmir.github.io/projects.html | rg "drawer-link" -c)
            echo "Projects page navigation links: $PROJECTS_NAV"

            echo "✅ Navigation functionality test complete"
          '

      - name: Ubuntu Fallback Test (Claude Compliant)
        if: failure()
        run: |
          sudo apt-get update -qq && sudo apt-get install -y curl
          echo "Fallback: Basic connectivity test"
          curl -s https://garmir.github.io/ | head -5
          echo "✅ Fallback test complete"

      - name: Generate Test Report
        run: |
          echo "GLOBE_AND_NAVIGATION_TEST_COMPLETE" > test-results.txt
          echo "Timestamp: $(date)" >> test-results.txt

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: globe-functionality-test-results
          path: "test-results.txt"
          retention-days: 1