name: Remote Repo Creation Test

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/remote-repo-test.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main

      - name: Test GH CLI
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          nix-shell -p github-cli --run 'gh auth status'
          nix-shell -p github-cli --run 'gh repo list garmir --limit 5'

      - name: Create Test File
        run: |
          echo "test content" > test.txt
          cat test.txt

      - name: Success
        run: echo "✅ Remote operations validated"
