name: Ultrathink Working (No Heredocs)

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ultrathink-working.yml'
      - '.claude/requests/*.txt'

jobs:
  ultrathink:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Framework
        run: |
          mkdir -p ~/.claude
          cp -r .claude/CORE ~/.claude/
          cp -r .claude/agents ~/.claude/ 2>/dev/null || true
          cp .claude/*.nix ~/.claude/ 2>/dev/null || true
          cp CLAUDE.md ~/.claude/ 2>/dev/null || true

      - name: Configure MCP
        run: |
          echo '{"mcpServers":{"sequential-thinking":{"command":"npx","args":["-y","@modelcontextprotocol/server-sequential-thinking"]}}}' > ~/.claude.json

      - name: Install Claude Code
        run: |
          nix-shell -p nodejs nodePackages.npm --run 'npm install -g @anthropic-ai/claude-code'

      - name: Read Request
        run: |
          if [ -f .claude/requests/latest.txt ]; then
            cp .claude/requests/latest.txt /tmp/request.txt
          else
            echo "Analyze repository compliance with ultrathink" > /tmp/request.txt
          fi

      - name: Execute Analysis
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          cd ~/.claude
          timeout 600 nix-shell -p nodejs --run 'npx @anthropic-ai/claude-code --help' || true

      - name: Collect Results
        if: always()
        run: |
          mkdir -p responses
          echo "Analysis complete" > responses/response-${{ github.run_id }}.txt
          find ~ -name "*result*" -o -name "*analysis*" -mmin -10 2>/dev/null | head -10 > responses/files-found.txt || true

      - name: Commit Response
        if: always()
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git config user.name "SuperClaude"
          git config user.email "superclaude@actions"
          git add responses/ 2>/dev/null || true
          git commit -m "response: ultrathink run ${{ github.run_id }}" 2>/dev/null || echo "No response"
          git push https://x-access-token:$GH_TOKEN@github.com/garmir/garmir.github.io.git main 2>/dev/null || echo "No changes"

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ultrathink-${{ github.run_id }}
          path: responses/
