name: SuperClaude Ultrathink Analysis

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ultrathink-simple.yml'

jobs:
  ultrathink:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Create Analysis Prompt
        run: |
          echo "Analyze SuperClaude Framework compliance violations. Focus: 1) Repository language classification (Python vs Nix), 2) Git hygiene and untracked files, 3) Shell script cleanup status, 4) Qwen3 integration. Use deep analysis with Sequential MCP." > /tmp/prompt.txt

      - name: Execute Ultrathink
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          cd /home/a/.claude
          nix-shell -p nodejs --run 'npx -y @anthropic-ai/claude-code "/sc:analyze --focus compliance --depth deep"'

      - name: Collect Results
        if: always()
        run: |
          ls -la /home/a/.claude/claudedocs/ 2>/dev/null || echo "No analysis directory"
