name: Ultrathink Final - Expect Automation

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ultrathink-final.yml'
      - '.claude/requests/*.txt'

jobs:
  ultrathink:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main

      - name: Install Framework
        run: |
          mkdir -p ~/.claude
          cp -r .claude/CORE ~/.claude/
          cp .claude/*.nix ~/.claude/ 2>/dev/null || true
          echo '{"mcpServers":{"sequential-thinking":{"command":"npx","args":["-y","@modelcontextprotocol/server-sequential-thinking"]}}}' > ~/.claude.json

      - name: Create Prompt File
        run: |
          mkdir -p /tmp/ultrathink
          printf 'Analyze SuperClaude Framework compliance violations.\n' > /tmp/ultrathink/prompt.txt
          printf 'Focus: repository language classification, git hygiene, framework separation.\n' >> /tmp/ultrathink/prompt.txt
          printf 'Use deep analysis with Sequential MCP.\n' >> /tmp/ultrathink/prompt.txt
          cat /tmp/ultrathink/prompt.txt

      - name: Create Expect Script
        run: |
          printf '#!/usr/bin/env expect\n' > /tmp/ultra.exp
          printf 'set timeout 900\n' >> /tmp/ultra.exp
          printf 'log_user 1\n' >> /tmp/ultra.exp
          printf 'log_file /tmp/expect-debug.log\n' >> /tmp/ultra.exp
          printf '\n' >> /tmp/ultra.exp
          printf 'set prompt [exec cat /tmp/ultrathink/prompt.txt]\n' >> /tmp/ultra.exp
          printf '\n' >> /tmp/ultra.exp
          printf 'spawn npx @anthropic-ai/claude-code --dangerously-skip-permissions $prompt\n' >> /tmp/ultra.exp
          printf '\n' >> /tmp/ultra.exp
          printf 'expect {\n' >> /tmp/ultra.exp
          printf '  -re {theme|style|Choose|Dark mode|Light mode} { send "1\\r"; exp_continue }\n' >> /tmp/ultra.exp
          printf '  -re {API key|api key|use this|Detected a custom} { send "1\\r"; exp_continue }\n' >> /tmp/ultra.exp
          printf '  -re {analytics|Analytics|telemetry} { send "n\\r"; exp_continue }\n' >> /tmp/ultra.exp
          printf '  -re {welcome|Welcome|started|get started|Let} { send "\\r"; exp_continue }\n' >> /tmp/ultra.exp
          printf '  -re {directory|workspace|project} { send "\\r"; exp_continue }\n' >> /tmp/ultra.exp
          printf '  -re {initialize|Initialize|setup|Setup} { send "y\\r"; exp_continue }\n' >> /tmp/ultra.exp
          printf '  -re {bypass|permissions|Bypass|allow|Allow} { send "2\\r"; exp_continue }\n' >> /tmp/ultra.exp
          printf '  -re {Continue|continue|Proceed|proceed} { send "\\r"; exp_continue }\n' >> /tmp/ultra.exp
          printf '  -re {.} { exp_continue }\n' >> /tmp/ultra.exp
          printf '  timeout { puts "\\nTimeout after 900s"; exit 1 }\n' >> /tmp/ultra.exp
          printf '  eof { puts "\\nProcess completed"; exit 0 }\n' >> /tmp/ultra.exp
          printf '}\n' >> /tmp/ultra.exp
          chmod +x /tmp/ultra.exp
          cat /tmp/ultra.exp

      - name: Execute Ultrathink
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          export ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY}"
          cd ~/.claude
          nix-shell -p expect nodejs --run "ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY} expect /tmp/ultra.exp"

      - name: Collect and Return
        if: always()
        run: |
          mkdir -p results

          # Copy expect debug log
          cp /tmp/expect-debug.log results/expect-debug-${{ github.run_id }}.log 2>/dev/null || echo "No debug log"

          # Find generated files
          find ~/.claude -name "*.md" -mmin -15 2>/dev/null > results/files-${{ github.run_id }}.txt || true

          # Copy any analysis outputs
          cp ~/.claude/claudedocs/*.md results/ 2>/dev/null || true

          echo "Analysis completed" > results/status-${{ github.run_id }}.txt

          git config user.name "Bot"
          git config user.email "bot@actions"
          git add results/ 2>/dev/null || true
          git commit -m "ultrathink results ${{ github.run_id }}" || true

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ultrathink-final-${{ github.run_id }}
          path: results/
